org: bloodyaugust
app: band-name
service: band-name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  curated:
    handler: handler.curated
    events:
      - http:
          path: /curated
          method: get
          cors: true
  random:
    handler: handler.random
    events:
      - http:
          path: /random
          method: get
          cors: true
